### PR TITLE
Better HTTP headers handling

### LINKED ISSUE #5: Whitelist / Blacklist headers
Right now almost all headers are copied

- from the client to the target server (request)
- from the target server to the client (response)

... which is not that great (some are redundant, some do not make sense, some crash the app, list `host`...).

Some headers have a "special role" and should not be forwarded as such :
- things regarding compression / gzip
- things regarding cookies

We should investigate which header can be safely forwarded and which cannot :

## Response headers

Cache-Control -> ✅
Content-Encoding -> ❌ (implies content decoding in memento)
Content-Security-Policy -> ✅
Content-Type -> ✅
Date -> ?
ETag -> ?
Expect-CT -> ?
Server -> ?
Set-Cookie -> ?
Strict-Transport-Security -> ?
Transfer-Encoding -> ❌
Vary -> ?
X-*-* -> ✅

## Request headers

Accept -> ✅
Accept-Encoding -> ❌
Accept-Language -> ✅
Cache-Control -> ✅
Connection -> ?
Cookie -> ?
Host -> ?
If-None-Match -> ?
Referer -> ?
Upgrade-Insecure-Requests -> ?
User-Agent -> ✅

### PR DESCRIPTION
**Pull request by antoinechalifour**
Should fix #5 .

### CODE REVIEW

File: src/infrastructure/service/NetworkServiceAxios.ts [hunk 1]
```diff
@@ -2,12 +2,68 @@ import axios, { AxiosResponse } from 'axios';
...
+    'content-length',
+  ];
+  const headers: Headers = {};
+
+  Object.keys(inputHeaders).forEach(key => {
+    if (HOP_BY_HOP_HEADERS.includes(key)) {
+      return;
+    }
+
+    headers[key.toLowerCase()] = inputHeaders[key];
```
Comment (antoinechalifour) [inline src/infrastructure/service/NetworkServiceAxios.ts]: Add a test for `toLowerCase`

File: src/infrastructure/service/NetworkServiceAxios.ts [hunk 2]
```diff
@@ -2,12 +2,68 @@ import axios, { AxiosResponse } from 'axios';
...
+  ];
+
+  const headers: Headers = {};
+
+  Object.keys(inputHeaders).forEach(key => {
+    if (EXCLUDED_HEADERS.includes(key)) {
+      return;
+    }
+
+    headers[key.toLowerCase()] = inputHeaders[key];
```
Comment (antoinechalifour) [inline src/infrastructure/service/NetworkServiceAxios.ts]: Add a test for `toLowerCase`

File: src/infrastructure/service/NetworkServiceAxios.test.ts [hunk 3]
```diff
@@ -0,0 +1,197 @@
...
+      })
+    );
+  });
+
+  it('should not forward response headers handled by memento', async () => {
+    // Given
+    ((axios as any) as jest.Mock).mockResolvedValue({
+      status: 200,
+      headers: {
+        'www-authenticate': 'Yes',
```
Comment (antoinechalifour) [inline src/infrastructure/service/NetworkServiceAxios.test.ts]: Uppercase in here

File: src/infrastructure/service/NetworkServiceAxios.test.ts [hunk 4]
```diff
@@ -0,0 +1,197 @@
...
+        age: 'Yes',
```
Comment (antoinechalifour) [inline src/infrastructure/service/NetworkServiceAxios.test.ts]: Use keys as values
